spring:
  datasource:
    url: jdbc:mysql://shuttle.proxy.rlwy.net:49057/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: oQOWDIpJfkKrUIGYsXIYyjWiqLCFgGFf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: prod
